# Generated by Django 4.1.7 on 2024-03-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='apellido',
            field=models.CharField(default='J', max_length=255),
        ),
    ]
