# Generated by Django 4.1.7 on 2024-03-19 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='apellido',
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
